# Image URL to use all building/pushing image targets
IMG ?= iter8-controller:latest
CRD_VERSION ?= v1alpha2
TELEMENTRY_VERSION ?= v2

all: manager

# Build manager binary
manager: generate fmt vet
	go build -o bin/manager github.com/iter8-tools/iter8-controller/cmd/manager

# Run against the Kubernetes cluster configured in $KUBECONFIG or ~/.kube/config
run: generate fmt vet load
	go run ./cmd/manager/main.go

# Generate iter8 crds and rbac manifests
manifests:
	go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd \
	  paths=./pkg/apis/iter8/${CRD_VERSION} output:crd:dir=./install/helm/iter8-controller/templates/crds/${CRD_VERSION}/
	./hack/crd_fix.sh ${CRD_VERSION}

# Prepare Kubernetes cluster for iter8 (running in cluster or locally):
#   install CRDs
#   install configmap/iter8-metrics is defined in namespace iter8 (creating namespace if needed)
load: manifests
	helm template install/helm/iter8-controller \
	  --name iter8-controller \
	  -x templates/default/namespace.yaml \
	  -x templates/crds/${CRD_VERSION}/iter8.tools_experiments.yaml \
	  -x templates/metrics/iter8_metrics.yaml \
	  -x templates/notifier/iter8_notifiers.yaml\
	  --set istioTelemetry=${TELEMENTRY_VERSION} \
	| kubectl apply -f -

# Deploy controller to the Kubernetes cluster configured in $KUBECONFIG or ~/.kube/config
deploy: manifests
	helm template install/helm/iter8-controller \
	  --name iter8-controller \
	  --set image.repository=`echo ${IMG} | cut -f1 -d':'` \
	  --set image.tag=`echo ${IMG} | cut -f2 -d':'` \
	  -x templates/default/namespace.yaml \
	  -x templates/default/serviceaccount.yaml \
	  -x templates/default/manager.yaml \
	  -x templates/crds/${CRD_VERSION}/iter8.tools_experiments.yaml \
	  -x templates/metrics/iter8_metrics.yaml \
	  -x templates/notifier/iter8_notifiers.yaml \
	  -x templates/rbac/role.yaml \
	  -x templates/rbac/role_binding.yaml \
	  --set istioTelemetry=${TELEMENTRY_VERSION} \
	| kubectl apply -f -

# Run go fmt against code
fmt:
	go fmt ./pkg/... ./cmd/...

# Run go vet against code
vet:
	go vet ./pkg/... ./cmd/...

# Generate code
generate:
ifndef GOPATH
	$(error GOPATH not defined, please define GOPATH. Run "go help gopath" to learn more about GOPATH)
endif
	go generate ./pkg/... ./cmd/...

# Build the docker image
docker-build:
	docker build . -t ${IMG}

# Push the docker image
docker-push:
	docker push ${IMG}

build-default: manifests
	echo '# Generated by make build-default; DO NOT EDIT' > install/iter8-controller.yaml
	helm template install/helm/iter8-controller \
   		--name iter8-controller \
		--set istioTelemetry=v1 \
	>> install/iter8-controller.yaml
	echo '# Generated by make build-default; DO NOT EDIT' > install/iter8-controller-telemetry-v2.yaml
	helm template install/helm/iter8-controller \
   		--name iter8-controller \
        --set istioTelemetry=v2 \
	>> install/iter8-controller-telemetry-v2.yaml

.PHONY: changelog
changelog:
	@sed -n '/$(ver)/,/=====/p' CHANGELOG | grep -v $(ver) | grep -v "====="

tests:
	go test ./test/. -v
	test/e2e/e2e.sh --skip-setup
