// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha2

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CandidateAssessment) DeepCopyInto(out *CandidateAssessment) {
	*out = *in
	in.VersionAssessment.DeepCopyInto(&out.VersionAssessment)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CandidateAssessment.
func (in *CandidateAssessment) DeepCopy() *CandidateAssessment {
	if in == nil {
		return nil
	}
	out := new(CandidateAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriterionAssessment) DeepCopyInto(out *CriterionAssessment) {
	*out = *in
	out.Statistics = in.Statistics
	out.ThresholdAssessment = in.ThresholdAssessment
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriterionAssessment.
func (in *CriterionAssessment) DeepCopy() *CriterionAssessment {
	if in == nil {
		return nil
	}
	out := new(CriterionAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RatioStatistics) DeepCopyInto(out *RatioStatistics) {
	*out = *in
	out.ImprovementOverBaseline = in.ImprovementOverBaseline
	out.CredibleInterval = in.CredibleInterval
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RatioStatistics.
func (in *RatioStatistics) DeepCopy() *RatioStatistics {
	if in == nil {
		return nil
	}
	out := new(RatioStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Statistics) DeepCopyInto(out *Statistics) {
	*out = *in
	out.RatioStatistics = in.RatioStatistics
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Statistics.
func (in *Statistics) DeepCopy() *Statistics {
	if in == nil {
		return nil
	}
	out := new(Statistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdAssessment) DeepCopyInto(out *ThresholdAssessment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdAssessment.
func (in *ThresholdAssessment) DeepCopy() *ThresholdAssessment {
	if in == nil {
		return nil
	}
	out := new(ThresholdAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionAssessment) DeepCopyInto(out *VersionAssessment) {
	*out = *in
	if in.CriterionAssessments != nil {
		in, out := &in.CriterionAssessments, &out.CriterionAssessments
		*out = make([]CriterionAssessment, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionAssessment.
func (in *VersionAssessment) DeepCopy() *VersionAssessment {
	if in == nil {
		return nil
	}
	out := new(VersionAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WinnerAssessment) DeepCopyInto(out *WinnerAssessment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WinnerAssessment.
func (in *WinnerAssessment) DeepCopy() *WinnerAssessment {
	if in == nil {
		return nil
	}
	out := new(WinnerAssessment)
	in.DeepCopyInto(out)
	return out
}
