apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v3-rollout-simple
spec:
  service:
    name: reviews
    baseline: reviews-v2
    candidates: [ "reviews-v3" ]
  criteria:
    - metric: iter8_mean_latency
      threshold:
        type: absolute
        value: 200 # milliseconds
